### ISSUE TITLE
As a god, I can add 2 players to a new team and name the new team.

### ISSUE THREAD

**Issue by bobbiejc** [HGHS2016/Assassin#14]
gods have to be able to add two players to a new team, and name the team

**Comment by jaboinga** [comment]
There is front end for this, no back end.

**Comment by bobbiejc** [comment]
We can get targetlist and teamlist that have exactly the same return.  this gives you the list teams and members.

Check the playerslist.

**Comment by bobbiejc** [comment]
Just added a function "unassignedplayers" to return the list of players that have no team.  it is tested through /createteam path

**Comment by bobbiejc** [comment]
Elliot saw your page, so we fixed app.js to restore the rendering of your page.  We created another /unassignedplayer to return teh unassigned players...

**Comment by bobbiejc** [comment]
You still get duplicate names in the both drop-down lists.  gods need to be careful.  You can reject this when you do the insert into database.

**Comment by bobbiejc** [comment]
Rebecca to validate what was done and close.

**Comment by jaboinga** [comment]
You can create a team and put it into cloudant.
