### ISSUE TITLE
As an Assassin I can log my kill.

### ISSUE THREAD

**Issue by bobbiejc** [HGHS2016/Assassin#9]
jobass [1:20 PM] 
assassins have to log their kills which sends a geoJSON to cloudant with other kill information

**Comment by bobbiejc** [comment]
When kill occurs 
- assassin needs to record the player's secret-id at the time and point of the kill
- we test the current location against the safe-zones 
- we write the kill information and the evidence (i.e. safe-zone status) to the database
- we reject the kill if it falls the rules of the gaine (i.e. occurs within a safe-zone.)
- otherwise we put the kill in pending approval state.

**Comment by jaboinga** [comment]
Added bigger kill button to the /home page.

**Comment by jaboinga** [comment]
Work in progress, but we did push some data up to cloudant.
